#pragma once
#include <memory>
#include <optional>
#include "core/compile/ir_linear/attr_base.hpp"
#include "core/compile/source/location.hpp"

namespace pepp::tc {
struct LinearIR {

  virtual ~LinearIR() = default;

  // Searches the linked list of attributes for one of the given type.
  // Must override if you inline an attribute into future IR lines.
  virtual AAttribute *attribute(int type);

  // Searches the linked list of attributes for one of the given type.
  // Must override if you inline an attribute into future IR lines.
  virtual const AAttribute *attribute(int type) const;

  // Override this method if you inline an attribute into future IR lines.
  virtual void insert(std::unique_ptr<AAttribute> attr);

  // Returns either: the number of bytes of object code generated by this line when placed at a specific address, or
  // nullopt. nullopt indicates that the line is not addressable (e.g., a CommentLine) and does not generate object
  // code. Any integer return value indicates that the line is addressable, and some number of object code bytes are
  // emitted. 0 is a special case that allows multiple IR lines to share an address, usually in the form of a .BLOCK
  // 0, which is used in macro expansions for handling multiple symbols per line. The default implementation returns
  // nullopt. If a machines address model uses <64 bits, keep only the low-order bits.
  virtual std::optional<u64> object_size(u64 base_address) const;

  // We had a pattern of casting base pointers to derived pointers in IR.
  // Derived types have wildly different behaviors even if they have the same API.
  // Instead of using true OO visitor pattern, I've opted for switch(type()) with static casts, which is a poor-mans
  // visitor.
  virtual int type() const = 0;

  template <typename Attribute> Attribute *typed_attribute() {
    static_assert(std::is_base_of_v<AAttribute, Attribute>, "Attribute must derive from attr::AAttribute");
    return dynamic_cast<Attribute *>(attribute(Attribute::TYPE));
  }
  template <typename Attribute> const Attribute *typed_attribute() const {
    static_assert(std::is_base_of_v<AAttribute, Attribute>, "Attribute must derive from attr::AAttribute");
    return dynamic_cast<const Attribute *>(attribute(Attribute::TYPE));
  }
  template <typename Attribute> bool has_attribute() const {
    static_assert(std::is_base_of_v<AAttribute, Attribute>, "Attribute must derive from attr::AAttribute");
    return attribute(Attribute::TYPE) != nullptr;
  }
  support::LocationInterval source_interval;
  // Head of linked list of additional attributes
  std::unique_ptr<AAttributeListNode> extended_attributes;
};
// Every deriving class must have a unique enum entry.
enum class LinearIRType : int {
  Empty,
  Comment,
  DotAlign,
  DotSymbol,
  DotBlock,
  DotEquate,
  DotLiteral,
  DotOrg,
  DotSection,
  DotConditional,
  MacroInstantiation,
  MacroDefinition,
  FirstUser,
};
} // namespace pepp::tc
