function(filter_targets_by_tag OUT_VAR IN_VAR PROP)
  set(inner_list "")
  foreach(TARGET IN LISTS IN_VAR)
    get_property(has_tag TARGET "${TARGET}" PROPERTY ${PROP})
    if("${has_tag}" STREQUAL "ON")
      #message("TARGET ${TARGET} has tag ${PROP}")
      LIST(APPEND inner_list ${TARGET})
    endif()
  endforeach()
  set(${OUT_VAR} "${inner_list}" PARENT_SCOPE)
endfunction()

macro(enumerate_targets OUT_VAR DIR)
    get_property(TGTS DIRECTORY "${DIR}" PROPERTY BUILDSYSTEM_TARGETS)

    foreach(TGT IN LISTS TGTS)
      LIST(APPEND ${OUT_VAR} ${TGT})
    endforeach()

    get_property(SUBDIRS DIRECTORY "${DIR}" PROPERTY SUBDIRECTORIES)
    foreach(SUBDIR IN LISTS SUBDIRS)
      enumerate_targets(${OUT_VAR} "${SUBDIR}")
    endforeach()
endmacro()

function(enumerate_tagged_targets OUT_VAR DIR PROP)
  enumerate_targets(enumerated ${DIR})
  filter_targets_by_tag(intermediate "${enumerated}" ${PROP})
  set(${OUT_VAR} "${intermediate}" PARENT_SCOPE)
endfunction()
