name: 'Install CMake & Qt'
inputs:
  qt_version:
    required: true
    default: '6.9.1'
  cache-key-prefix:
    required: false
runs:
  using: "composite"
  # Selectively install and configure LLVM
  steps:
    - name: Install CMake and Ninja
      uses: lukka/get-cmake@v3.27.9
    - uses: actions/checkout@v4
      with:
        repository: 'Matthew-McRaven/install-qt-action'
        ref: '0fd226b72bc5b5a74f0baa65de4eae9d32b8f7d6'
        path: 'install-qt-action'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: install-qt-action/action/
    # Windows has an old python which causes aqt to fail at runtime.
    - name: Force update python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    # Must allow breaking system packages on Mac OS runners, else setup fails.
    # See: https://github.com/jurplel/install-qt-action/issues/252
    - name: Set up pip config on macOS
      if: runner.os == 'macOS'
      run: |
        mkdir -p ~/.config/pip
        echo "[global]" > ~/.config/pip/pip.conf
        echo "break-system-packages = true" >> ~/.config/pip/pip.conf
      shell: bash
    - name: Build Matthew-McRaven/install-qt-action
      run: |
        cd install-qt-action/action/
        npm ci || npm install
        npm run build
      shell: bash
    - name: Install Qt
      uses: ./install-qt-action/action/
      with:
        version: ${{ inputs.qt_version }}
        cache: true
        extra: "--base https://mirrors.ocf.berkeley.edu/qt"
        tools: 'tools_ifw,qt.tools.ifw.47'
        modules: 'qtshadertools qtimageformats'
